ぐるなびサイト完成のコミット
tes-inc/internship-20190204 pull request #6
Opened 2019-02-28 08:47 UTC by A-Tanahashi

## ぐるなびAPIを使用した検索サイト
### ◉機能リスト
+ 検索機能
	+ 店名検索入力フォーム...お店の名前で検索することが出来ます。
	+ フリーワード検索入力フォーム...好きなキーワードを入れて検索することが出来ます。
	+ Find!!(全件検索ボタン) ...全国にあるお店を検索出来ます。
	+ Near!!(周辺検索ボタン(3000m))...現在地から3000m以内にあるお店が検索出来ます。
+ 検索結果(10件ずつ表示)
	+ 店舗情報...各店舗は店名または写真をクリックするとぐるなびの各店舗のページへ移動します。マウスカーソルを合わせる事で店名も写真も色が変化し選択されているのがわかりやすい様にしています。
	+ 前へ、次へ...画面を下へ850pxスクロールした際に画面の左右中央に固定で表示され押すことで前ページまたは次ページへ移動します。
	+ page top...画面を下へ850pxスクロールした際に右下に固定で表示され押すことでページのトップへ戻ることが出来ます。
+ 画面表示
	+ メディアクエリを使用し、画面幅に合わせて店舗情報や検索フォーム、ボタン、サイトタイトル等が変化する様にしてあります。

2019-03-01 01:26 UTC, A-Tanahashi commented
@d-yamauchi @KouyamaAtsushi お疲れ様です。お手数お掛けしますがレビューをお願い致します。

2019-03-01 05:40 UTC, KouyamaAtsushi commented
## 良いところ

- **デザイン性が高い**

　開いた瞬間のインパクトとデザイン性の高いページ操作ボタンやフォントを使用している点。シンプルなのも良いです。ボタンがスクロールすると出てくるアイディアも画面構成を邪魔しないので良いと思いました。

- **動きのある画面**

　店舗情報が1店舗ずつ並んでボタン操作やウィンドウサイズによって動くのは楽しいです。

- **ローディング中の表示がわかりやすい**

　ローディング中であることを表す表示がパッと見てわかりやすいのは良いと思いました。

## 気になるところ

- **ウィンドウサイズ**

　これは私の方がひどいのですが、ウィンドウサイズによってはデザインが崩れてしまう点

- **よりオシャレに**

　すごくオシャレなので検索フォームやそのボタンもデザインされていると更にオシャレになりそうだと思いました。

- **コードに関して**

・私もそうだったのですが、長くなってしまっている部分は「`」を使うと見やすくなります。
・知らなかった関数やajaxの書き方など参考になりました。
・変数名にはコメントで何が入る変数なのか書いておくと、後で見返す時など分かりやすくなるかなと思いました。

2019-03-01 05:44 UTC, A-Tanahashi commented on Tanahashi/gourmetSearch/main.css
> +  #shopName{
test

2019-03-01 05:46 UTC, A-Tanahashi commented on Tanahashi/gourmetSearch/index.js
> +  let page = 1;
ここはGoodですね！
テスト

2019-03-01 05:46 UTC, A-Tanahashi commented on Tanahashi/gourmetSearch/index.js
> +    $('#kekka').fadeIn();
test

2019-03-01 06:13 UTC, A-Tanahashi commented
@d-yamauchi @KouyamaAtsushi [WIP]付けました。

2019-03-04 02:14 UTC, A-Tanahashi commented
### 修正箇所
- __page top__ ...850pxスクロールだと検索結果のページになってからさらに少し下へ行かないと表示されなくわかりづらいと思ったので750pxに変更しました。
- __前へ(5ページ単位)、次へ(5ページ単位)__…1ページ単位のページ送りだけだと不便かと思い、次へと前へボタンにカーソルを合わせると5ページ単位でページ遷移できるボタンを追加しました。
- __ページ数__…何ページ目だけの表示から〇〇ページ分の何ページという表示に変更し今全体のどのあたりにいるのかわかりやすい様に変更しました。
<img width="1266" alt="2019-03-04 10 25 37" src="https://user-images.githubusercontent.com/47583183/53706325-300c9880-3e6d-11e9-8065-11b626e75795.png">

- __画面表示__
	- pxで指定していたところを%に直したり、ボタンや結果の並び等を変えてレイアウトを修正しました。
	- フォームと検索ボタン…フォームはボーダーを消して半透明にし背景と少し馴染む感じにしました。ボタンは色を変えて、ホバーを追加し選択していることがすぐわかる様に変更しました。
-コード…変数の部分を`${~}`に変更したのとコメントの追加をしました。

![2019-03-04 11 01 03](https://user-images.githubusercontent.com/47583183/53706349-4f0b2a80-3e6d-11e9-8610-83b677c3704d.png)

2019-03-04 02:21 UTC, A-Tanahashi commented
@KouyamaAtsushi お疲れ様です。レビューで良い部分と気になる部分両方あげていただきありがとうございました。指摘をしてもらったところを中心に修正したのでご確認をよろしくお願い致します！
@d-yamauchi お疲れ様です。神山さんから頂いたレビューの対応が完了しWIPを外しましたのでよろしくお願い致します。

2019-03-04 02:59 UTC, KouyamaAtsushi commented
レビュー対応ありがとうございます。
デザインが更に良くなったうえにページ送り機能もついて使いやすくもなっていますね！
レイアウトに関しては教えていただきたいくらいです！
コードのコメントも追加してくださってありがとうございました。
LGTMです！

![LGTM](http://66.media.tumblr.com/7981f8da8ec9396b54d5913e897097f3/tumblr_ocf3akroNS1uyzky1o1_1280.jpg)

2019-03-04 04:47 UTC, d-yamauchi requested changes
とても見栄えの良いサイトでした！！
ミニ講座で出したWeb Fontやアニメーションなども取り入れられていて嬉しいです！

気になるところをコメントしましたので、確認をお願いします。

2019-03-04 04:47 UTC, d-yamauchi commented on Tanahashi/gourmetSearch/index.js
> +        <p class="cp_imghover cp_bw"><img src="${dateArray[i].image_url.shop_image1}" alt="No Image!!"></a></p>
2点あります。

1 画像があってもなくてもaltが「No Image!!」になってしまうと思います。

\<img\>のaltは、確かに画像が読み込めなかったときに表示される文字列ではあるのですが、
本来の役割としては、画像の説明を書くところになります。
　→ちなみにですが、目が見えない人が読み上げソフトを使ってサイトを見たときに、画像部分はaltが読み上げられます。
ですので、画像がある場合・無い場合のどっちにも対応したaltにしたほうが良いと思います。

2 aタグはタグを跨がらないように書いた方が読みやすいと思います。
今はこんな風にかかれています（一部簡略化しています）。
```html
<p>
  <a>タイトル // ここには終了タグを書いていない
<p>
<hr>
<p>
  <img></a> // ここに終了タグがある
</p>
```
タグAの中にタグBを書いた場合は、タグAの中でタグBの終了タグを書いたほうが読みやすくなります。
　→開始タグと終了タグの関係を探すのが大変になると思います。
　→記憶が定かではないのですが、文法的にもNGな書き方だったと思います。

上記2つをまとめて直す場合、こんなやり方はどうでしょうか。
（ついでに、HTML文字列に改行を入れて見やすくしてみました）
```js
$.each(dateArray, function (i) {
  // 画像がある場合とない場合で条件分岐
  const img = dateArray[i].image_url.shop_image1
    ? `<img src="${dateArray[i].image_url.shop_image1}" alt="No Image!!"></a>`
    : "<div>No Image!!<div>";

  $('table').append(`
    <tr>
      <td class="animated slideInRight">
        <p id="title">
          <a href="${dateArray[i].url}" target="blank">◉${dateArray[i].name}</a>
        </p>
        <hr>
        <p class="cp_imghover cp_bw">
          <a href="${dateArray[i].url}" target="blank">${img}</a>
        </p>
        <p id="place">
          ${dateArray[i].address}<br>${dateArray[i].tel}
        </p>
        <p id="pr">
          ${dateArray[i].pr.pr_short}
        </p>
      </td>
    </tr>
  `);
});
```
（↑は、No Imageのレイアウトが変わってしまうので別途CSSなどを書く必要があります）

2019-03-04 04:47 UTC, d-yamauchi commented on Tanahashi/gourmetSearch/index.js
> +      $('#offsetPage').append(`<p id="total">Find:全${date.total_hit_count}件-${page}/${Math.round(date.total_hit_count/10)}page-</p>`);
> Math.round(date.total_hit_count/10)

全ページ数を計算している箇所ですが、
例えば、検索ヒット件数が43件だった場合ページ数は5ページになるはずですが、4ページと表示されてしまいます。
「アイス」で現在地検索をすると↓のような表示になりました。
![2019-03-04 13 44 13](https://user-images.githubusercontent.com/18714698/53711060-a9af8100-3e83-11e9-91e1-6d3cd0df17c1.jpg)

`Math.round()` は四捨五入なので、切り上げをしてくれる `Math.ceil()`の方が良いかなと思います。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil

2019-03-04 07:13 UTC, A-Tanahashi commented on Tanahashi/gourmetSearch/index.js
> +      $('#offsetPage').append(`<p id="total">Find:全${date.total_hit_count}件-${page}/${Math.round(date.total_hit_count/10)}page-</p>`);
レビューありがとうございます。レビューを頂いた以下の部分を修正致しましたので、お手数ですがご確認よろしくお願い致します。
***

### 修正箇所2

+ 総ページ数の表示…Math.ceil()を使い切り上げに変更しました。
<img width="521" alt="2019-03-04 15 59 49" src="https://user-images.githubusercontent.com/47583183/53716041-f5b7f100-3e96-11e9-81f2-950c2f971bc8.png">

+ 店舗画像…画像がある場合とない場合どちらにも対応したaltにし、ご提案して頂いた方法でaタグの修正、それに伴うcssでのレイアウト修正をしました。
<img width="1252" alt="2019-03-04 16 01 15" src="https://user-images.githubusercontent.com/47583183/53716031-f05aa680-3e96-11e9-847a-92f3f8e096c9.png">

2019-03-05 00:47 UTC, d-yamauchi approved these changes
修正ありがとうございます！！
レスポンシブ対応してあってハイテクですね。
LGTMです！


![LGTM](http://66.media.tumblr.com/316dac01b18e4041e1049d86286ac2be/tumblr_o97u3i4bs11r4frruo1_400.gif)

2019-03-05 00:49 UTC, KouyamaAtsushi approved these changes

2019-03-05 00:50 UTC, merged