ajaxを用いたレストラン検索サイト
tes-inc/internship-20190204 pull request #7
Opened 2019-02-28 08:59 UTC by KouyamaAtsushi

## 目的

- ajaxを用いた非同期通信によるレストラン検索

## 機能

- 店名・フリーワードによる検索
- GPSを用いて指定した範囲内での検索
- ユーザーの使用を想定した便利なページ移動機能

### TOPページ
<img width="724" alt="2019-02-28 17 26 08" src="https://user-images.githubusercontent.com/47583174/53552118-fb9f9080-3b7d-11e9-8055-a0256bcd4036.png">
店名・フリーワード・検索範囲を指定して「Let'sぐるぐる!」ボタンクリックで検索開始。

### 検索結果画面
<img width="643" alt="2019-02-28 17 31 25" src="https://user-images.githubusercontent.com/47583174/53552478-bd56a100-3b7e-11e9-8e1a-38a0e3dadf05.png">
店名と範囲を指定して検索した結果。
検索数と現在のページが表示され、「againぐるぐる？」ボタンクリックで条件を変えてもう一度検索することができます。

### 店舗情報
<img width="529" alt="2019-02-28 17 36 28" src="https://user-images.githubusercontent.com/47583174/53552748-6bfae180-3b7f-11e9-8978-10139ca98e1b.png">
検索されたお店の情報はページ下部に10件ごと表示されます。

### ヘッダー
<img width="592" alt="2019-02-28 17 39 34" src="https://user-images.githubusercontent.com/47583174/53552947-ddd32b00-3b7f-11e9-96cf-a3bc9bcbb2b7.png">

### フッター
<img width="539" alt="2019-02-28 17 39 05" src="https://user-images.githubusercontent.com/47583174/53552948-e166b200-3b7f-11e9-8daa-ba905320800a.png">
ヘッダーとフッター両方にページめくり機能をつけ操作しやすくしています。

2019-03-01 00:44 UTC, KouyamaAtsushi commented
@d-yamauchi @A-Tanahashi ようやくレストラン検索サイトが完成いたしました。お手数ですがレビューの方よろしくお願い致します。

2019-03-01 04:54 UTC, A-Tanahashi commented
#### -良かったと思ったところ-
1. 検索のボタンが一つになっていてアニメーションまでついていたので押したくなるし検索しやすかったし、検索の範囲を選べる様になっているのも良かったです。
1. 上にも下にもページ移動出来る項目やページ内を移動出来る項目があって便利でした。
1. コードの部分でコメントが丁寧に書かれていて何の処理をしているのかとても分かり易かったです。
1. 連結の部分が＋ではなく`${〜}`を使用していて読みやすかったです。
***
#### -少し気になったところ-
1. 駐車場とwifiの部分がどこもundefinedになってしまっていました。
1. 画像がない時に表示される画像が何も知らない人が見た時にその店舗の写真だと思ってしまう可能性があるかもしれないと思ったので、No Image等の文字が入っていた方が良いかもしれないと思いました。
1. ページボタンが1~100まで表示されていたりして視界に入った時に少し表示が多い印象を受けました。

2019-03-01 06:06 UTC, d-yamauchi commented on kouyama/resNavi/script.js
> +// 次の10件を表示
```suggestion
// 次の10件を表示。
```

2019-03-01 06:07 UTC, d-yamauchi commented on kouyama/resNavi/script.js
> +// 次の10件を表示
最後に句点をつけると良いと思います。
```suggestion
// 次の10件を表示。
```

2019-03-04 00:59 UTC, KouyamaAtsushi commented
## レビュー指摘の対応(店舗表示情報の変更・代替画像の変更・ページボタンの改善・不要なCSSの消去)
### 店舗情報の変更
表示できない値を参照していたので別の情報に変更
<img width="599" alt="2019-03-04 9 38 51" src="https://user-images.githubusercontent.com/47583174/53704628-a5726c00-3e61-11e9-9b29-e64921cf5639.png">

### 代替画像の変更
ご指摘の通り分かりにくかったので画像が存在しないことを表す画像に変更
<img width="580" alt="2019-03-04 9 42 29" src="https://user-images.githubusercontent.com/47583174/53704647-da7ebe80-3e61-11e9-8cf8-6b393029d185.png">

### ページボタンの改善
11ページを超える場合10ページ進められるボタンが現れるように変更
<img width="711" alt="2019-03-04 9 43 50" src="https://user-images.githubusercontent.com/47583174/53704663-0bf78a00-3e62-11e9-8102-569ade1d6272.png">

### その他
検索ボタンのどこを押しても反応するように変更

2019-03-04 01:34 UTC, KouyamaAtsushi commented
@A-Tanahashi レビューありがとうございます。良い部分についても挙げていただけて嬉しかったです！
指摘していただいた点に関する対応が完了致しました。ご確認のほどよろしくお願い致します。

@d-yamauchi レビュー対応が完了しましたので、再度レビュー依頼をお送りします。よろしくお願い致します。

2019-03-04 02:41 UTC, A-Tanahashi commented
ご対応して頂きありがとうございます。ページボタンめちゃくちゃ見やすくなってて良かったです！LGTMです！

![LGTM](http://68.media.tumblr.com/c35dd400164d15970a0afe73b131a779/tumblr_or9xt6g2p91ub5poho1_250.jpg)

2019-03-04 07:18 UTC, d-yamauchi requested changes
G**gleも顔負けの検索サイトですね！
フォントやアニメーションなど、以前よりデザインが上がってきて良いですね！
　→簡単にそれっぽいデザインを作れるのがWebの強みですよね。

2点コメントしましたので確認をお願いします。

2019-03-04 07:18 UTC, d-yamauchi commented on kouyama/resNavi/script.js
> +  data = { keyid : keyid }; // 前回の検索dataを初期化
__こういう書き方もありますよという紹介なので、変更はしなくても大丈夫です。__

ECMAScript2015から実装された新しいオブジェクトの書き方があります。
こんな書き方になります。
```js
data = {keyid};
```

`{ keyid : keyid }`のようにキー名と値の変数名が一緒の場合は、キー名を省略できます。
タイプ数が減って幸せになれます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Object_initializer#ECMAScript_2015_での新しい表記法

もう一つ例を出します。
```js
const name = "hoge";
const age = 25;
const job = "student"
const person = {name, age, job};
  // -> personの値： {name: "hoge", age: 25, job: "student"} になる。
```

2019-03-04 07:18 UTC, d-yamauchi commented on kouyama/resNavi/script.js
> +  if (!$search_name && !$free_word && !$range) { // 店名・フリーワード・範囲どれも入力されていない場合
検索ワードが無いときに`alert()`が呼ばれる処理ですが、`$range`が意図しないものになっているように見えます。
検索ワードも範囲も指定しない状態で検索ボタンを押すと、`$range`には"0"（文字列）が入ります。
"0"はtrue扱いのものなので、否定`!`をつけるとfalseになります。

つまり、条件式がこんな感じになります。
```js
// 検索ワードも範囲も指定しない状態で検索ボタンを押した場合
if (true && true && false) {
  alert('検索ワードを入力してください');
  return;
}
```

単純に"0"かどうかをみるのはどうでしょうか。
```suggestion
  if (!$search_name && !$free_word && $range === "0") { // 店名・フリーワード・範囲どれも入力されていない場合
```

2019-03-04 08:32 UTC, KouyamaAtsushi commented
@d-yamauchi レビューありがとうございます！レビュー指摘の対応を致しました。
オブジェクトの書き方については書き換えなくても良いとのことでしたがkeyidの部分だけ変えてみました。
$rangeについては明らかに判定がおかしかったので、指摘していただいて気付づくことができました。
お忙しい中ありがとうございました！

2019-03-05 00:44 UTC, d-yamauchi approved these changes
対応ありがとうございます！！
良いサイトが出来ましたね。
LGTMです！

![LGTM](http://nyago-nyago-muyuu.up.n.seesaa.net/nyago-nyago-muyuu/image/Dance1.gif?d=a135)

2019-03-05 00:49 UTC, A-Tanahashi approved these changes

2019-03-05 00:50 UTC, merged